accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import helloworld, AccountCreateView, AccountDetailView, AccountUpdateView

app_name = "accountapp"

urlpatterns = [
                    # FBV에선 함수 이름을 바로 사용해서 불러올 수 있다.
    path('helloworld/', helloworld, name='helloworld'),
                    # CBV에선 Class이름 뒤에 .as_view()를 붙인다.
    path('create/', AccountCreateView.as_view(), name='create'),
    path('login/', LoginView.as_view(template_name = 'accountapp/login.html'), name = 'login'),
    path('logout/', LogoutView.as_view(), name='logout'),
          # 해당 유저 정보를 골라오기 위해 Primary Key를 인자값으로 가져온다.
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
]

pragmatic/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accountapp.urls')),
]

accountapp/models.py
from django.db import models

# Create your models here.


class HelloWorld(models.Model):
    text = models.CharField(max_length=255, null=False)

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm

class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].disabled = True

accountapp/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView

from accountapp.forms import AccountUpdateForm
from accountapp.models import HelloWorld


def helloworld(request):
    #요청이 POST 방식일 경우
    if request.method == "POST":
        # 변수 temp에 POST방식으로 받은 요청 중 'hello_world_input에 대한 정보를 저장
        temp = request.POST.get('hello_world_input')
        # 변수 new_hello_world에 accountapp.model에 있는 HelloWorld model을 저장 (DB 불러오기)
        new_hello_world = HelloWorld()
        # 변수 안에 들어있는 text에 변수 temp를 저장 (DB에 입력)
        new_hello_world.text = temp
        # 해당 정보를 저장 (DB에 저장)
        new_hello_world.save()

        # 작업이 완료 된 뒤에는 'account/helloworld/'으로 재접속. (새로고침 시 DB에 Data가 중복되어 쌓이는 것을 방지)
                                    # reverse 함수는 url을 즉시 생성하고, 반환한다. view를 실행할 때마다 호출.
        return HttpResponseRedirect(reverse('accountapp:helloworld'))

    #요청이 GET 방식일 경우
    else:
        # 변수 hello_world_list에 HelloWorld DB안에 있는 모든 객체를 저장
        hello_world_list = HelloWorld.objects.all()
                                                              # 추가적인 Data 꾸러미 안에 'text'라는 이름을 가진 'GET METHOD!!'라는 내용을 넣어서 저장
        return render(request, 'accountapp/hello_world.html', context={'hello_world_list':hello_world_list})

# Django Generic에 있는 CreateView를 상속 받는 Class를 생성
class AccountCreateView(CreateView):
    # User는 Django에서 기본 제공 해주는 model 이다.
    model = User # 어느 Model을 사용할 것인가?
    form_class = UserCreationForm # 어는 Form을 사용할 것인가?
                  # revers_lazy 함수는 url이 필요한 시점에 url을 생성하고 반환한다. 현재 구문에서 success_url (성공 시) 이기 때문에 reverse_lazy를 사용.
    success_url = reverse_lazy('accountapp:helloworld') # 성공 시 어느 url로 전달할 것인가?
    template_name = 'accountapp/create.html' # 어떤 template를 보여줄 것인가?

# Django Generic에 있는 DetailView를 상속 받는 Class 생성
class AccountDetailView(DetailView):
    # Django 기본제공 Model - User 사용
    model = User
    # 다른 사람의 정보를 볼 때 기본 user 사용 시 내 정보를 투영하여 보기 때문에 따로 설정이 필요
    context_object_name = 'target_user'
    # 읽어온 정보를 출력할 template만 필요하므로 template_name만 필요.
    template_name = 'accountapp/detail.html'

class AccountUpdateView(UpdateView):
    model = User
    form_class = AccountUpdateForm
    success_url = reverse_lazy('accountapp:helloworld')
    template_name = 'accountapp/update.html'

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block content %}

  <div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div class="mb-4">
      <h4>Sign Up</h4>
    </div>
                  <!-- accountapp 내부에 있는 create에 routing -->
    <form action="{% url 'accountapp:create' %}" method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
  </div>


{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block content %}

    <div>
        <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
            <p>
                {{ target_user.date_joined }}
            </p>
            <h2 style="font-family: 'NanumSquareNeoOTF-Bd'">
                {{ target_user.username }}
            </h2>
            <!-- 선택한 유저 정보가 지금 접속한 유저 정보와 같다면 -->
            {% if target_user == user %}
            <a href="{% url 'accountapp:update' pk=user.pk %}">
                <p>
                    Change Info
                </p>
            </a>
            {% endif %}
        </div>
    </div>


{% endblock %}

accountapp/templates/accountapp/hello_world.html
{% extends 'base.html' %}

{% block content %}

    <div style="border-radius: 1rem; margin: 2rem; text-align: center">
      <!-- 구글 폰트 중 'lobster'를 사용, 없으면 '필기체 계열' 폰트 사용 -->
      <h1 style="font-family: 'lobster', cursive;">
          Hello World LIST!
      </h1>
      <!-- method에 GET, POST 방식인지를 설정 -->
      <form action="/account/helloworld/" method="post">
          <!-- Django를 이용해서 POST 방식으로 보낼 땐 csrf_token이 필요하다 이유는 crsf 취약점을 이용한 악의적인 공격으로 부터 보호하기 위함-->
          {% csrf_token %}
          <div>
            <!-- input의 name은 input으로 받을 Data에 대한 구분이라 생각하면 된다. -->
            <input type="text" name="hello_world_input">
          </div>
          <div>
            <input type="submit" class="btn btn-primary" value="POST">
          </div>
      </form>

      <!-- views.py에서 hello_world_list가 존재한다면 -->
      {% if hello_world_list %}
        <!-- hello_world 안에 있는 hello_world_list(배열)을 반복해서 -->
        {% for hello_world in hello_world_list %}
          <h4>
              <!-- hello_world안에 text를 불러오기 -->
              {{ hello_world.text }}
          </h4>
        <!-- for문 종료 -->
        {% endfor %}
      <!-- if문 종료 -->
      {% endif %}
    </div>

{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

  <div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div>
      <h4>Login</h4>
    </div>
    <div>
      <form action="" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
      </form>
    </div>
  </div>

{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block content %}

  <div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div class="mb-4">
      <h4>Change Info</h4>
    </div>
    <form action="{% url 'accountapp:update' pk=user.pk %}" method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
  </div>


{% endblock %}